//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSakudaira
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Plato
    {
        public int Num_Plato { get; set; }
        public string Detalle { get; set; }
    }
}
