//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSakudaira
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SakudairaEntities : DbContext
    {
        public SakudairaEntities()
            : base("name=SakudairaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Detalle_Plato> Detalle_Plato { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Plato> Plato { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
    }
}
