//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSakudaira
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int Num_Reserva { get; set; }
        public int Num_Mesa { get; set; }
        public int Num_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Reserva { get; set; }
    }
}
